### ISSUE TITLE
Fix "Password" Section on "Create Profile" Page

### ISSUE THREAD

**Issue by StevenEgnaczyk** [TriangleFraudternity/Chalk_Bets#33]
When you go to create a profile, there are a few errors:
* We should tell the user what the password requirements are before they make it
* There should be a confirm password section
* The default text should not be "Tell me about yourself"
* Error message should look more like an error message and not just text on the screen (DO NOT DO THIS YET, there are tickets for css formatting,)

![Image](https://github.com/TriangleFraudternity/Chalk_Bets/assets/33490385/6d6d2f2a-d698-4085-bdae-e525fe3846df)

**Comment by zzteddy** [comment]
dont think we should say reqs before, most websites do not
